name: Deploy with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # === FRONTEND ===
      - name: Install frontend dependencies
        working-directory: ./
        run: npm install

      - name: Build frontend
        working-directory: ./
        run: npm run build

      - name: Upload frontend to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_NAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./"
          strip_components: 1
          target: ${{ secrets.FTP_FOLDER }}
          overwrite: true

      - name: Set ownership to nodejs
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            chown -R nodejs:nodejs ${{ secrets.FTP_FOLDER }}

      # === PM2 RESTART ===
      - name: Restart both apps via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo -u nodejs bash -c '
              cd ${{ secrets.FTP_FOLDER }}
              npm ci
              pm2 reload ecosystem.config.cjs --env production
            '
